### ISSUE TITLE
Unknown error (0x80005000)

### ISSUE THREAD

**Issue by anon-jpg** [nidem/kerberoast#13]
Exception calling "FindAll" with "0" argument(s): "Unknown error (0x80005000)"
At C:\SD\scripts\sc\user\GetUserSPNS.ps1:98 char:5
+     $results = $searcher.FindAll()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

**Comment by anon-jpg** [comment]
`GetUserSPNS.ps1`

**Comment by mdanilor** [comment]
I am getting the same issue here. Did you ever find out how to fix it?

**Comment by anon-jpg** [comment]
> I am getting the same issue here. Did you ever find out how to fix it?

Unfortunately nope

**Comment by nidem** [comment]
What options are you using? Is there a `\` anywhere in any of your params?

**Comment by mdanilor** [comment]
No... I just tried running it without any parameters. 
However, it is very unlikely that the problem lies in kerberoast itself. In my computer it worked fine, but not on the target machine (I'm trying to solve an AD pentest lab). The VBScript did not work either. Ideas are welcome :)  
If I ever solve this, I shall post here.

**Comment by nidem** [comment]
Since this isn't a script issue, I'm going to close this issue.

If I had to guess, it would have to do with the resolution of the GC.
